.PHONY: clean All

All:
	@echo "----------Building project:[ Cpp_by_doing - Debug ]----------"
	@"$(MAKE)" -f  "Cpp_by_doing.mk"
clean:
	@echo "----------Cleaning project:[ Cpp_by_doing - Debug ]----------"
	@"$(MAKE)" -f  "Cpp_by_doing.mk" clean
